# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ECE/Desktop/project4/project4.cache/wt [current_project]
set_property parent.project_path C:/Users/ECE/Desktop/project4/project4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  {C:/Users/ECE/Desktop/project4/project4.srcs/sources_1/imports/[Lab04]_Verilog_files/opcodes.v}
  {C:/Users/ECE/Desktop/project4/project4.srcs/sources_1/imports/[Lab04]_Verilog_files/regfile.v}
  {C:/Users/ECE/Desktop/project4/project4.srcs/sources_1/imports/[Lab04]_Verilog_files/ALU.v}
  {C:/Users/ECE/Desktop/project4/project4.srcs/sources_1/imports/[Lab04]_Verilog_files/cpu.v}
}
synth_design -top RF -part xc7vx485tffg1157-1
write_checkpoint -noxdef RF.dcp
catch { report_utilization -file RF_utilization_synth.rpt -pb RF_utilization_synth.pb }
